# file_content=open("file.txt")
# print(file_content.read())
# file=open("file.txt","w")
# file.write("this is new content")
# file.close()
file_content=open("file.txt","w")
file_content.write("\n")
file_content.write("this is another content")
file_content.close()